namespace SpriteKind {
    export const Arrow = SpriteKind.create()
    export const MiniDisplay = SpriteKind.create()
    export const BigDisplay = SpriteKind.create()
    export const longSnake = SpriteKind.create()
}
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    currentBodyPart = (currentBodyPart + 3) % 4
    setCurrentBodyPartArrows(currentBodyPart)
})
function createMiniCharacter () {
    miniMeImage = minifyImage(img`
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ..................................dddddddddddddddd....................
        .................................dddddddddddddddddd...................
        ................................ddddddddddddddddddd...................
        ................................dddddddddddddddddddd..................
        ................................dddddddddddddddddddd..................
        ................................dddddddddddddddddddd..................
        ................................dddddddddddddddddddd..................
        ................................ddddddddddddddddddddd.................
        ................................ddddddddddddddddddddd.................
        ................................dddddddddddddddddddddd................
        ................................dddddddddddddddddddddd................
        ................................dddddddddddddddddddddd................
        .................................ddddddddddddddddddddd................
        .................................ddddddddddddddddddddd................
        .................................ddddddddddddddddddddd................
        ................................ddddddddddddddddddddd.................
        ...............................dddddddddddddddddddddd.................
        ..............................dddddddddddddddddddddd..................
        .............................dddddddddddddddddddddd...................
        ............................ddddddddddddddddddddd.....................
        ............................ddddddddddddddddddddd.....................
        ...........................dddddddddddddddddddddd.....................
        .........................dddddddddddddddddddddddd.....................
        ........................ddddddddddddddddddddddddd.....................
        .......................dddddddddddddddddddddddddd.....................
        .....................dddddddddddddddddddddddddddd.....................
        ...........dddd.....dddddddddddddddddddddddddddd......................
        ...........bbbd....ddddddddddddddddddddddddddddd......................
        ........dddbbbdd..dddddddddddddddddddddddddddddd......................
        .......dddddbbdd.dddddddddddddddddddddddddddddd.......................
        .......ddddbbbbbbdddddddddddddddddddddddddddddd.......................
        .......dddbbbbbbddddddddddddddddddddddddddddddd.......................
        .......dddbbbbbbdddddddddddddddddddddddddddddd........................
        .......dbbbbbbbbdddddddddddddddddddddddddddddd........................
        ........bbbbbbbddddddddddddddddddddddddddddddd........................
        ........bbbbbbbddddddddddddddddddddddddddddddd........................
        ........bbbbbbbddddddddddddddddddddddddddddddd........................
        ........bbbbbb.dddddddddddddddddddddddddddddddb.......................
        ..........bb...dddddddddddddddddddddddddddddddb.......................
        ...............dddddddddddddddddddddddddddddddb.......................
        ...............ddddddddddddddddddddddddddddddbb.......................
        ................dddddddddddddddddddddddddddddbbb......................
        .................dddddddddddddddddddddddddddbbbb......................
        .................dddddddddddddddddddddddddddbbbb......................
        ..................dddddddddddddddddddddddddbbbbb......................
        ...................ddddddddddddddddddddddddbbbbb......................
        .....................dddddddddddddddddddddbbbbbb......................
        ......................ddddddddddddddddddddbbbbbb......................
        ........................dddddddddddddddddbbbbbbb......................
        ............................ddddddddddddbbbbbbbb......................
        ................................dddddbbbbbbbbbb.......................
        .....................................bbbbbbbbbd.......................
        ......................................bbbbbbddd.......................
        .......................................dddddddd.......................
        .......................................dddddddd.......................
        ........................................ddddddd.......................
        ........................................ddddddd.......................
        .........................................dddddd.......................
        .........................................ddddddd......................
        ..........................................dddddd......................
        ...........................................ddddddddf..................
        ...........................................dddddddd...................
        ............................................dddddddf..................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        `, 70, 90)
    copyImage(miniMeImage, miniEars.image, imageWidthArray[0] / 2, imageHeightArray[0] / 2, 14, 1)
    copyImage(miniMeImage, miniFace.image, imageWidthArray[1] / 2, imageHeightArray[1] / 2, 16, 9)
    copyImage(miniMeImage, miniCostume.image, imageWidthArray[2] / 2, imageHeightArray[2] / 2, 9, 17)
    copyImage(miniMeImage, minifyImage(img`
        ddddddbb..........
        ddddddddbb........
        dddddddddb........
        dddddddddbb.......
        ddddddddddb.......
        ddddddddddb.......
        ddddddddddbb......
        dddddddddddbb.....
        dddddddddddbb.....
        dddddddddddbb.....
        dddddddddddbb.....
        dddddddddddbb.....
        dddddddddddbb.....
        .ddddddddddb......
        ..dddddddddb......
        ..dddddddddb......
        ..dddddddddb......
        ..dddddddddb......
        ...dddddddbb......
        ...ddddddbb.......
        ...ddddddbb.......
        ....dddddbb.......
        ....dddddbbb......
        .....dddddbb......
        ......ddddddd.....
        .......dddddd.....
        .......dddddd.....
        ........dddddd....
        .........ddddddd..
        ..........ddddddd.
        ...........ddddddf
        .............dddf.
        `, 18, 32), 9, 16, 10, 29)
    copyImage(miniMeImage, miniArms.image, imageWidthArray[3] / 2, imageHeightArray[3] / 2, 16, 20)
    miniMeImageRun = minifyImage(img`
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ..................................dddddddddddddddd....................
        .................................dddddddddddddddddd...................
        ................................ddddddddddddddddddd...................
        ................................dddddddddddddddddddd..................
        ................................dddddddddddddddddddd..................
        ................................dddddddddddddddddddd..................
        ................................dddddddddddddddddddd..................
        ................................ddddddddddddddddddddd.................
        ................................ddddddddddddddddddddd.................
        ................................dddddddddddddddddddddd................
        ................................dddddddddddddddddddddd................
        ................................dddddddddddddddddddddd................
        .................................ddddddddddddddddddddd................
        .................................ddddddddddddddddddddd................
        .................................ddddddddddddddddddddd................
        ................................ddddddddddddddddddddd.................
        ...............................dddddddddddddddddddddd.................
        ..............................dddddddddddddddddddddd..................
        .............................dddddddddddddddddddddd...................
        ............................ddddddddddddddddddddd.....................
        ............................ddddddddddddddddddddd.....................
        ...........................dddddddddddddddddddddd.....................
        .........................dddddddddddddddddddddddd.....................
        ........................ddddddddddddddddddddddddd.....................
        .......................dddddddddddddddddddddddddd.....................
        .....................dddddddddddddddddddddddddddd.....................
        ...........dddd.....dddddddddddddddddddddddddddd......................
        ...........bbbd....ddddddddddddddddddddddddddddd......................
        ........dddbbbdd..dddddddddddddddddddddddddddddd......................
        .......dddddbbdd.dddddddddddddddddddddddddddddd.......................
        .......ddddbbbbbbdddddddddddddddddddddddddddddd.......................
        .......dddbbbbbbddddddddddddddddddddddddddddddd.......................
        .......dddbbbbbbdddddddddddddddddddddddddddddd........................
        .......dbbbbbbbbdddddddddddddddddddddddddddddd........................
        ........bbbbbbbddddddddddddddddddddddddddddddd........................
        ........bbbbbbbddddddddddddddddddddddddddddddd........................
        ........bbbbbbbddddddddddddddddddddddddddddddd........................
        ........bbbbbb.dddddddddddddddddddddddddddddddb.......................
        ..........bb...dddddddddddddddddddddddddddddddb.......................
        ...............dddddddddddddddddddddddddddddddb.......................
        ...............ddddddddddddddddddddddddddddddbb.......................
        ................dddddddddddddddddddddddddddddbbb......................
        .................dddddddddddddddddddddddddddbbbb......................
        .................dddddddddddddddddddddddddddbbbb......................
        ..................dddddddddddddddddddddddddbbbbb......................
        ...................ddddddddddddddddddddddddbbbbb......................
        .....................dddddddddddddddddddddbbbbbb......................
        ......................ddddddddddddddddddddbbbbbb......................
        ........................dddddddddddddddddbbbbbbb......................
        ............................ddddddddddddbbbbbbbb......................
        ................................dddddbbbbbbbbbb.......................
        .....................................bbbbbbbbbd.......................
        ......................................bbbbbbddd.......................
        .......................................dddddddd.......................
        .......................................dddddddd.......................
        ........................................ddddddd.......................
        ........................................ddddddd.......................
        .........................................dddddd.......................
        .........................................ddddddd......................
        ..........................................dddddd......................
        ..........................................dddddd......................
        ...........................................ddddd......................
        ...........................................dddddd.....................
        ...........................................dddddd.....................
        ............................................ddddddddf.................
        ............................................dddddddd..................
        .............................................dddddddf.................
        ......................................................................
        ......................................................................
        ......................................................................
        `, 70, 90)
    copyImage(miniMeImageRun, miniEars.image, imageWidthArray[0] / 2, imageHeightArray[0] / 2, 14, 1)
    copyImage(miniMeImageRun, miniFace.image, imageWidthArray[1] / 2, imageHeightArray[1] / 2, 16, 9)
    copyImage(miniMeImageRun, miniCostume.image, imageWidthArray[2] / 2, imageHeightArray[2] / 2, 9, 17)
    copyImage(miniMeImageRun, minifyImage(img`
        ddddddbb..........
        ddddddddbb........
        dddddddddb........
        dddddddddbb.......
        ddddddddddb.......
        ddddddddddb.......
        ddddddddddbb......
        dddddddddddbb.....
        ddddddddddbbb.....
        ddddddddddbbb.....
        ddddddddddbbb.....
        .dddddddddbbb.....
        .dddddddddbbb.....
        ..dddddddbb.......
        ..ddddddbb........
        ..ddddddbb........
        ...dddddbb........
        ...dddddbbb.......
        ....dddddbb.......
        .....ddddddd......
        ......dddddd......
        ......dddddd......
        .......dddddd.....
        ........ddddddd...
        .........ddddddd..
        ..........ddddddf.
        ............dddf..
        ..................
        ..................
        ..................
        ..................
        ..................
        `, 18, 32), 9, 16, 10, 29)
    copyImage(miniMeImageRun, miniArms.image, imageWidthArray[3] / 2, imageHeightArray[3] / 2, 16, 20)
    miniMe = sprites.create(miniMeImage, SpriteKind.Player)
    animation.runImageAnimation(
    miniMe,
    [miniMeImage, miniMeImageRun],
    200,
    true
    )
    miniMe.bottom = 120
    miniMe.ay = 700
    miniMe.setFlag(SpriteFlag.StayInScreen, true)
}
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (!(gameStarted)) {
        for (let value of sprites.allOfKind(SpriteKind.Arrow)) {
            value.destroy()
        }
        for (let value of sprites.allOfKind(SpriteKind.Text)) {
            value.destroy()
        }
        for (let value of sprites.allOfKind(SpriteKind.MiniDisplay)) {
            value.destroy()
        }
        for (let value of sprites.allOfKind(SpriteKind.BigDisplay)) {
            value.destroy()
        }
        createMiniCharacter()
        startGame()
    } else {
        miniMe.vy = -200
    }
})
function startGame () {
    gameStarted = true
}
function areColorsVeryDifferent (c1: number, c2: number, c3: number, c4: number) {
    nonZero = 0
    if (c1 != 0) {
        nonZero += 1
    }
    if (c2 != 0) {
        nonZero += 1
    }
    if (c3 != 0) {
        nonZero += 1
    }
    if (c4 != 0) {
        nonZero += 1
    }
    average = (c1 + c2 + (c3 + c4)) / nonZero
    standardDeviation = 0
    if (c1 != 0) {
        standardDeviation += (c1 - average) ** 2
    }
    if (c2 != 0) {
        standardDeviation += (c2 - average) ** 2
    }
    if (c3 != 0) {
        standardDeviation += (c3 - average) ** 2
    }
    if (c4 != 0) {
        standardDeviation += (c4 - average) ** 2
    }
    return Math.sqrt(standardDeviation / nonZero) > 2
}
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    currentCostumeIndex = imageIndex[currentBodyPart]
    if (currentCostumeIndex > 0) {
        if (currentBodyPart == 0) {
            animation.runMovementAnimation(
            earsArrowLeft,
            "l -5 0 l 5 0",
            100,
            false
            )
        } else if (currentBodyPart == 1) {
            animation.runMovementAnimation(
            faceArrowLeft,
            "l -5 0 l 5 0",
            100,
            false
            )
        } else if (currentBodyPart == 2) {
            animation.runMovementAnimation(
            costumeArrowLeft,
            "l -5 0 l 5 0",
            100,
            false
            )
        } else {
            animation.runMovementAnimation(
            armsArrowLeft,
            "l -5 0 l 5 0",
            100,
            false
            )
        }
        currentCostumeIndex += -1
        imageIndex[currentBodyPart] = currentCostumeIndex
        setImage(currentBodyPart)
    }
})
function setCurrentBodyPartArrows (bodyPart: number) {
    for (let value of sprites.allOfKind(SpriteKind.Arrow)) {
        value.image.replace(9, 6)
    }
    if (bodyPart == 0) {
        earsArrowLeft.image.replace(6, 9)
        earsArrowRight.image.replace(6, 9)
    } else if (bodyPart == 1) {
        faceArrowLeft.image.replace(6, 9)
        faceArrowRight.image.replace(6, 9)
    } else if (bodyPart == 2) {
        costumeArrowLeft.image.replace(6, 9)
        costumeArrowRight.image.replace(6, 9)
    } else {
        armsArrowLeft.image.replace(6, 9)
        armsArrowRight.image.replace(6, 9)
    }
}
function makeCostumeMenu () {
    textSprite = textsprite.create("Costume", 0, 10)
    textSprite.setPosition(120, 60)
    miniCostume = sprites.create(minifyImage(costume[0], 32, 36), SpriteKind.MiniDisplay)
    miniCostume.setPosition(120, 75)
    costumeArrowLeft = sprites.create(img`
        . . . 6 8 . . . . . . . . 
        . . 6 6 8 . . . . . . . . 
        . 6 6 6 6 6 6 6 6 6 6 8 . 
        6 6 6 6 6 6 6 6 6 6 6 6 8 
        . 6 6 6 8 8 8 8 8 8 8 8 . 
        . . 6 6 8 . . . . . . . . 
        . . . 6 8 . . . . . . . . 
        `, SpriteKind.Arrow)
    costumeArrowLeft.setPosition(95, 75)
    costumeArrowRight = sprites.create(img`
        . . . . . . . . 8 6 . . . 
        . . . . . . . . 8 6 6 . . 
        . 8 6 6 6 6 6 6 6 6 6 6 . 
        8 6 6 6 6 6 6 6 6 6 6 6 6 
        . 8 8 8 8 8 8 8 8 6 6 6 . 
        . . . . . . . . 8 6 6 . . 
        . . . . . . . . 8 6 . . . 
        `, SpriteKind.Arrow)
    costumeArrowRight.setPosition(145, 75)
}
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    currentCostumeIndex = imageIndex[currentBodyPart]
    if (currentCostumeIndex < allImages[currentBodyPart].length - 1) {
        if (currentBodyPart == 0) {
            animation.runMovementAnimation(
            earsArrowRight,
            "l 5 0 l -5 0",
            100,
            false
            )
        } else if (currentBodyPart == 1) {
            animation.runMovementAnimation(
            faceArrowRight,
            "l 5 0 l -5 0",
            100,
            false
            )
        } else if (currentBodyPart == 2) {
            animation.runMovementAnimation(
            costumeArrowRight,
            "l 5 0 l -5 0",
            100,
            false
            )
        } else {
            animation.runMovementAnimation(
            armsArrowRight,
            "l 5 0 l -5 0",
            100,
            false
            )
        }
        currentCostumeIndex += 1
        imageIndex[currentBodyPart] = currentCostumeIndex
        setImage(currentBodyPart)
    }
})
function minifyImage (input2: Image, inputX: number, inputY: number) {
    smallImage = image.create(Math.ceil(inputX / 2), Math.ceil(inputY / 2))
    for (let x = 0; x <= inputX / 2; x++) {
        for (let y = 0; y <= inputY / 2; y++) {
            if (areColorsVeryDifferent(input2.getPixel(x * 2, y * 2), input2.getPixel(x * 2 + 1, y * 2), input2.getPixel(x * 2, y * 2 + 1), input2.getPixel(x * 2 + 1, y * 2 + 1))) {
                smallImage.setPixel(x, y, input2.getPixel(x * 2, y * 2))
            } else {
                newColor = 0
                numColors = 0
                if (input2.getPixel(x * 2, y * 2) != 0) {
                    newColor += input2.getPixel(x * 2, y * 2)
                    numColors += 1
                }
                if (input2.getPixel(x * 2 + 1, y * 2) != 0) {
                    newColor += input2.getPixel(x * 2 + 1, y * 2)
                    numColors += 1
                }
                if (input2.getPixel(x * 2, y * 2 + 1) != 0) {
                    newColor += input2.getPixel(x * 2, y * 2 + 1)
                    numColors += 1
                }
                if (input2.getPixel(x * 2 + 1, y * 2 + 1) != 0) {
                    newColor += input2.getPixel(x * 2 + 1, y * 2 + 1)
                    numColors += 1
                }
                newColor = newColor / numColors
                smallImage.setPixel(x, y, newColor)
            }
        }
    }
    return smallImage
}
function copyImage (destination: Image, picToCopy: Image, width: number, height: number, x: number, y: number) {
    for (let i = 0; i <= width; i++) {
        for (let j = 0; j <= height; j++) {
            if (picToCopy.getPixel(i, j) != 0) {
                destination.setPixel(x + i, y + j, picToCopy.getPixel(i, j))
            }
        }
    }
}
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    currentBodyPart = (currentBodyPart + 1) % 4
    setCurrentBodyPartArrows(currentBodyPart)
})
function makeEarsMenu () {
    textSprite = textsprite.create("Ears", 0, 10)
    textSprite.setPosition(120, 10)
    miniEars = sprites.create(minifyImage(ears[0], 28, 12), SpriteKind.MiniDisplay)
    miniEars.setPosition(120, 21)
    earsArrowLeft = sprites.create(img`
        . . . 6 8 . . . . . . . . 
        . . 6 6 8 . . . . . . . . 
        . 6 6 6 6 6 6 6 6 6 6 8 . 
        6 6 6 6 6 6 6 6 6 6 6 6 8 
        . 6 6 6 8 8 8 8 8 8 8 8 . 
        . . 6 6 8 . . . . . . . . 
        . . . 6 8 . . . . . . . . 
        `, SpriteKind.Arrow)
    earsArrowLeft.setPosition(95, 21)
    earsArrowRight = sprites.create(img`
        . . . . . . . . 8 6 . . . 
        . . . . . . . . 8 6 6 . . 
        . 8 6 6 6 6 6 6 6 6 6 6 . 
        8 6 6 6 6 6 6 6 6 6 6 6 6 
        . 8 8 8 8 8 8 8 8 6 6 6 . 
        . . . . . . . . 8 6 6 . . 
        . . . . . . . . 8 6 . . . 
        `, SpriteKind.Arrow)
    earsArrowRight.setPosition(145, 21)
}
sprites.onDestroyed(SpriteKind.longSnake, function (sprite) {
    if (0 < sprite.right) {
        projectile2 = sprites.createProjectileFromSide(img`
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ...6666666666...
            ..667777777766..
            .66777777777766.
            6777777777777766
            771f1777771f1776
            7711177777111777
            7777777777777777
            7777777777777777
            `, -50, 0)
        animation.runImageAnimation(
        projectile2,
        [img`
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ...6666666666...
            ..667777777766..
            .66777777777766.
            6777777777777766
            771f1777771f1776
            7711177777111777
            7777777777777777
            7777777777777777
            `,img`
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ....66666666....
            ...6666666666...
            ..66ffffffff66..
            ..6f66666666f66.
            .6f6777777776f6.
            .667777777777666
            6777777777777766
            771f1777771f1776
            7711177777111777
            7777777777777777
            7777777777777777
            `,img`
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ....6666666.....
            ...6f1f1f1f66...
            ..66fffffffff6..
            .6ff1f1f1f1fff6.
            .6ff666666661f6.
            6f16777777776f66
            6667777777777666
            6777777777777766
            771f1777771f1776
            7711177777111777
            7777777777777777
            7777777777777777
            `,img`
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ....66666666....
            ...6666666666...
            ..66ffffffff66..
            ..6f66666666f66.
            .6f6777777776f6.
            .667777777777666
            6777777777777766
            771f1777771f1776
            7711177777111777
            7777777777777777
            7777777777777777
            `],
        100,
        true
        )
        projectile2.bottom = 120
        projectile2.x = sprite.x
        projectile2.setKind(SpriteKind.longSnake)
    }
})
function setImage (bodyPart: number) {
    currentCostumeIndex = imageIndex[bodyPart]
    bodyPartSprites[bodyPart].setImage(allImages[bodyPart][currentCostumeIndex])
    miniSprites[bodyPart].setImage(minifyImage(allImages[bodyPart][currentCostumeIndex], imageWidthArray[bodyPart], imageHeightArray[bodyPart]))
}
function setup () {
    scene.setBackgroundColor(1)
    rabbitBear = sprites.create(img`
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ......................................................................
        ..................................dddddddddddddddd....................
        .................................dddddddddddddddddd...................
        ................................ddddddddddddddddddd...................
        ................................dddddddddddddddddddd..................
        ................................dddddddddddddddddddd..................
        ................................dddddddddddddddddddd..................
        ................................dddddddddddddddddddd..................
        ................................ddddddddddddddddddddd.................
        ................................ddddddddddddddddddddd.................
        ................................dddddddddddddddddddddd................
        ................................dddddddddddddddddddddd................
        ................................dddddddddddddddddddddd................
        .................................ddddddddddddddddddddd................
        .................................ddddddddddddddddddddd................
        .................................ddddddddddddddddddddd................
        ................................ddddddddddddddddddddd.................
        ...............................dddddddddddddddddddddd.................
        ..............................dddddddddddddddddddddd..................
        .............................dddddddddddddddddddddd...................
        ............................ddddddddddddddddddddd.....................
        ............................ddddddddddddddddddddd.....................
        ...........................dddddddddddddddddddddd.....................
        .........................dddddddddddddddddddddddd.....................
        ........................ddddddddddddddddddddddddd.....................
        .......................dddddddddddddddddddddddddd.....................
        .....................dddddddddddddddddddddddddddd.....................
        ...........dddd.....dddddddddddddddddddddddddddd......................
        ...........bbbd....ddddddddddddddddddddddddddddd......................
        ........dddbbbdd..dddddddddddddddddddddddddddddd......................
        .......dddddbbdd.dddddddddddddddddddddddddddddd.......................
        .......ddddbbbbbbdddddddddddddddddddddddddddddd.......................
        .......dddbbbbbbddddddddddddddddddddddddddddddd.......................
        .......dddbbbbbbdddddddddddddddddddddddddddddd........................
        .......dbbbbbbbbdddddddddddddddddddddddddddddd........................
        ........bbbbbbbddddddddddddddddddddddddddddddd........................
        ........bbbbbbbddddddddddddddddddddddddddddddd........................
        ........bbbbbbbddddddddddddddddddddddddddddddd........................
        ........bbbbbb.dddddddbbddddddddddddddddddddddb.......................
        ..........bb...dddddddddbbddddddddddddddddddddb.......................
        ...............ddddddddddbddddddddddddddddddddb.......................
        ...............ddddddddddbbddddddddddddddddddbb.......................
        ...............dddddddddddbddddddddddddddddddbbb......................
        ...............dddddddddddbdddddddddddddddddbbbb......................
        ...............dddddddddddbbddddddddddddddddbbbb......................
        ...............ddddddddddddbbddddddddddddddbbbbb......................
        ...............ddddddddddddbbddddddddddddddbbbbb......................
        ...............ddddddddddddbbdddddddddddddbbbbbb......................
        ...............ddddddddddddbbdddddddddddddbbbbbb......................
        ...............ddddddddddddbbddddddddddddbbbbbbb......................
        ................dddddddddddbbdddddddddddbbbbbbbb......................
        .................ddddddddddb....dddddbbbbbbbbbb.......................
        ..................dddddddddb.........bbbbbbbbbd.......................
        ..................dddddddddb..........bbbbbbddd.......................
        ..................dddddddddb...........dddddddd.......................
        ..................dddddddddb...........dddddddd.......................
        ...................dddddddbb............ddddddd.......................
        ...................ddddddbb.............ddddddd.......................
        ...................ddddddbb..............dddddd.......................
        ....................dddddbb..............ddddddd......................
        ....................dddddbbb..............dddddd......................
        .....................dddddbb..............dddddd......................
        ......................ddddddd..............ddddd......................
        .......................dddddd..............dddddd.....................
        .......................dddddd..............dddddd.....................
        ........................dddddd..............ddddddddf.................
        .........................ddddddd............dddddddd..................
        ..........................ddddddd............dddddddf.................
        ...........................ddddddf....................................
        .............................dddf.....................................
        ......................................................................
        `, SpriteKind.BigDisplay)
    rabbitBear.setPosition(41, 54)
    earsSprite = sprites.create(img`
        ...666666...................
        .666666666........6666666...
        666699999666....6666666666..
        666999999966....66669999966.
        666999999966....66669999996.
        6669999999966....66699999966
        6669999999966....66699999966
        6669999999996....66699999996
        6669999999996.....666999999.
        .6669999999.........6999999.
        .6669999....................
        ...66.......................
        `, SpriteKind.BigDisplay)
    earsSprite.setPosition(47, 17)
    costumeSprite = sprites.create(img`
        ...............222..............
        ..............22222.............
        .............2222222............
        ............22222222222.........
        ...........222222222222222222222
        ...........222222222222222222552
        ..........4422222222222222222552
        ........444422222222222222222224
        .......4444442222222222222222224
        ......44444444222222222222222224
        ....4444444444422222222222225544
        ...4444444444444222222222222554.
        ..44444444444444222222222222224.
        .444444444444444422222222222244.
        444444444444444444222222222224..
        444444444444444444222222222224..
        .44444444444444444422222225544..
        ..444444444444444442222222554...
        ...44444444444444444222222224...
        ....4444444444444444222222224...
        .....444444444444444422222224...
        ......44444444444444422225524...
        .......4444444444444442225524...
        .........44444444444444222224...
        .........44444444444444222224...
        ..........444444444444442222....
        ..........444444444444442222....
        ..........44444444444444222.....
        ...........4444444444444422.....
        ............44444444444442......
        ............44444444444444......
        ............4444444444444.......
        ............4444444444444.......
        ............444444444444........
        ............44444444444.........
        ...............44444............
        `, SpriteKind.BigDisplay)
    costumeSprite.setPosition(39, 62)
    armsSprite = sprites.create(img`
        ddddd...................................
        ddddd...................................
        dddddd..................................
        ddddddd.................................
        .ddddddd................................
        ..ddddddd...............................
        ...dddddddd.............................
        ...dddddddddd...........................
        ....dddddddddddd........................
        .....ddddddddddddd......................
        ......ddddddddddddd6666.................
        ..........ddddddddd...66................
        ...............6........6...............
        ..............6..........6..............
        ..............6..........66.............
        ..............6...........6.............
        ..............6...........6.............
        ..............6..........66.............
        ..............6666666666666.............
        ..............6688888888866.............
        ..............6668888888666.............
        ..............6666666666666.............
        ..............66c66666666c6.............
        ..............66c666c66c6c6.............
        ..............66c666c66c6c6.............
        ..............66c666c66c6c6.............
        ..............66c666c66c666.............
        ...............6c666c666c66.............
        ...............66666c666c6..............
        ........................................
        `, SpriteKind.BigDisplay)
    armsSprite.setPosition(59, 60)
    facePaintSprite = sprites.create(img`
        .......................
        .......................
        .......................
        .......................
        ....6..................
        ....6.............6....
        ..6.666...........6....
        ..66.66..........666...
        ...66666.........6f1...
        66.6ff16.........6ff...
        .666fff6.........6666..
        .666fff6...............
        ...66666...............
        .66666...........3333..
        .66...............33...
        ......6666.............
        .....666......cc..c..cc
        .....66........c..c..c.
        ...............cccfccc.
        ................cfffc..
        .......................
        .......................
        `, SpriteKind.BigDisplay)
    facePaintSprite.setPosition(50, 38)
    makeEarsMenu()
    makeFacepaintMenu()
    makeCostumeMenu()
    makeArmsMenu()
    currentBodyPart = 0
    allImages = [ears, face, costume, arms]
    imageIndex = [1, 0, 1, 0]
    bodyPartSprites = [earsSprite, facePaintSprite, costumeSprite, armsSprite]
    miniSprites = [miniEars, miniFace, miniCostume, miniArms]
    imageWidthArray = [28, 22, 32, 40]
    imageHeightArray = [20, 22, 36, 30]
    setCurrentBodyPartArrows(currentBodyPart)
    for (let i = 0; i <= 3; i++) {
        setImage(i)
    }
}
function makeFacepaintMenu () {
    textSprite = textsprite.create("Face", 0, 10)
    textSprite.setPosition(120, 35)
    miniFace = sprites.create(minifyImage(face[0], 22, 18), SpriteKind.MiniDisplay)
    miniFace.setPosition(120, 47)
    faceArrowLeft = sprites.create(img`
        . . . 6 8 . . . . . . . . 
        . . 6 6 8 . . . . . . . . 
        . 6 6 6 6 6 6 6 6 6 6 8 . 
        6 6 6 6 6 6 6 6 6 6 6 6 8 
        . 6 6 6 8 8 8 8 8 8 8 8 . 
        . . 6 6 8 . . . . . . . . 
        . . . 6 8 . . . . . . . . 
        `, SpriteKind.Arrow)
    faceArrowLeft.setPosition(95, 47)
    faceArrowRight = sprites.create(img`
        . . . . . . . . 8 6 . . . 
        . . . . . . . . 8 6 6 . . 
        . 8 6 6 6 6 6 6 6 6 6 6 . 
        8 6 6 6 6 6 6 6 6 6 6 6 6 
        . 8 8 8 8 8 8 8 8 6 6 6 . 
        . . . . . . . . 8 6 6 . . 
        . . . . . . . . 8 6 . . . 
        `, SpriteKind.Arrow)
    faceArrowRight.setPosition(145, 47)
}
function makeArmsMenu () {
    textSprite = textsprite.create("Arms", 0, 10)
    textSprite.setPosition(120, 90)
    miniArms = sprites.create(minifyImage(arms[0], 40, 30), SpriteKind.MiniDisplay)
    miniArms.setPosition(120, 104)
    armsArrowLeft = sprites.create(img`
        . . . 6 8 . . . . . . . . 
        . . 6 6 8 . . . . . . . . 
        . 6 6 6 6 6 6 6 6 6 6 8 . 
        6 6 6 6 6 6 6 6 6 6 6 6 8 
        . 6 6 6 8 8 8 8 8 8 8 8 . 
        . . 6 6 8 . . . . . . . . 
        . . . 6 8 . . . . . . . . 
        `, SpriteKind.Arrow)
    armsArrowLeft.setPosition(95, 104)
    armsArrowRight = sprites.create(img`
        . . . . . . . . 8 6 . . . 
        . . . . . . . . 8 6 6 . . 
        . 8 6 6 6 6 6 6 6 6 6 6 . 
        8 6 6 6 6 6 6 6 6 6 6 6 6 
        . 8 8 8 8 8 8 8 8 6 6 6 . 
        . . . . . . . . 8 6 6 . . 
        . . . . . . . . 8 6 . . . 
        `, SpriteKind.Arrow)
    armsArrowRight.setPosition(145, 104)
}
let projectile: Sprite = null
let facePaintSprite: Sprite = null
let armsSprite: Sprite = null
let costumeSprite: Sprite = null
let earsSprite: Sprite = null
let rabbitBear: Sprite = null
let miniSprites: Sprite[] = []
let bodyPartSprites: Sprite[] = []
let projectile2: Sprite = null
let numColors = 0
let newColor = 0
let smallImage: Image = null
let allImages: Image[][] = []
let textSprite: TextSprite = null
let armsArrowRight: Sprite = null
let costumeArrowRight: Sprite = null
let faceArrowRight: Sprite = null
let earsArrowRight: Sprite = null
let armsArrowLeft: Sprite = null
let costumeArrowLeft: Sprite = null
let faceArrowLeft: Sprite = null
let earsArrowLeft: Sprite = null
let imageIndex: number[] = []
let currentCostumeIndex = 0
let standardDeviation = 0
let average = 0
let nonZero = 0
let gameStarted = false
let miniMe: Sprite = null
let miniMeImageRun: Image = null
let miniArms: Sprite = null
let miniCostume: Sprite = null
let miniFace: Sprite = null
let imageHeightArray: number[] = []
let imageWidthArray: number[] = []
let miniEars: Sprite = null
let miniMeImage: Image = null
let currentBodyPart = 0
let arms: Image[] = []
let costume: Image[] = []
let face: Image[] = []
let ears: Image[] = []
ears = [img`
    ............................
    ............................
    ............................
    ............................
    ............................
    ............................
    ............................
    ............................
    ............................
    ...666666...................
    .666666666..................
    666699999666....6666666.....
    666999999966..6666666666....
    666999999966..66669999966...
    6669999999966.66669999996...
    6669999999966..6669999996...
    .669999999996..6669999996...
    .669999999996..666999999....
    ..66999999996...66699999....
    ..66999999996.....69999.....
    `, img`
    ............................
    ........f11111111111111.....
    ........f11111111111111f....
    ........ff111ffffffffffff...
    .........ffffffffffffffff...
    .......b.ffffffffffffffff...
    .......b.ffffffffff11ffff...
    .......b.fffffffff11ffff....
    .......bbffffffff11fffff.b..
    .......bbfffffffffffffffbb..
    .......bbfffffffffffffffbb..
    .......bbffffffffffffffbb...
    ........bbfffffffffffffbb...
    ........bbffffffffffffbb....
    ........bbffffffffffffbb....
    ........bbf222fffffffbb.....
    ........bbf222fffffffb......
    ........bbb222fffffffb.f....
    .....ff.bbb222fffffffbff....
    .....fffffffffffffffffff....
    `, img`
    ............................
    ............................
    ............................
    ............................
    ............................
    ...fffffff........fffff.....
    ...fffffffffffffffffffff....
    .............f..............
    .......c.....f.....c........
    .......cc....f.....c........
    .......cc....f.....cc.......
    .......ccc...f....ccc.......
    .......ccc...f....cccc......
    .......ccc.222222.cccc......
    .......ccc222222222ccc......
    ......2ccc2222222222cc......
    ......2cccc222222222ccc.....
    ......2cccc2222222222cc.....
    .....22cccc2222222222222222.
    .....22cccc2222222222222222.
    `, img`
    ............................
    ....f11111111111111.........
    ....f11111111111111f........
    ....ff111ffffffffffff.......
    .....ffffffffffffffff.......
    .....ffffffffffffffff.......
    .....ffffffffff11ffff.......
    .....fffffffff11ffff........
    .....ffffffff11fffff........
    .....fffffffffffffff........
    .....fffffffffffffff........
    .....ffffffffffffff.........
    .....ffffffffffffff.........
    .....fffffffffffff..........
    .....fffffffffffff..........
    ......f222fffffff...........
    ......f222fffffff...........
    ......f222fffffff..f........
    .ff..ff222fffffff.ff........
    .fffffffffffffffffff........
    `]
face = [
img`
    ......................
    ......................
    ......................
    ......................
    ....6.................
    ....6.............6...
    ..6.666...........6...
    ..66.66..........666..
    ...66666.........6f1..
    66.6ff16.........6ff..
    .666fff6.........6666.
    .666fff6..............
    ...66666..............
    .66666...........3333.
    .66...............33..
    ......6666............
    .....666......cc..c..c
    .....66........c..c..c
    ...............cccfccc
    ................cfffc.
    ......................
    ......................
    `,
img`
    ...ccccccccccccccc....
    .cccccccccccccccccc...
    .cccccccccccccccccc...
    ccccccccccccccccccc...
    ccccccccccccccccccc...
    ccccccccccccccccccc...
    cccccccccccccccccccc..
    ccccccccccccccccccccc.
    ccccccccccccccccccf1cf
    ccccff1cccccccccccffcf
    ccccfffccccccccccccccf
    ccccfffcccccccccccccfc
    cccccccccccccccccccfcc
    ccccccccccccccccc3ffcc
    ffffffffffffffffffcccc
    cccccccccccccccccccfcc
    ccfccfccfccfccfccfcfcc
    ccfccfccfccfccfccfcfc.
    ccfccfccfccfccfccfccc.
    .ccccfccfccfccfccccc..
    ..cccfccfccfccccccc...
    ....ccccccccccc.......
    `,
img`
    ......................
    ......................
    .......ffffff.........
    .....ffffffffff.......
    ....fffffffffffff.....
    ...fffffffffffffff....
    ..ffffffffffffffffff..
    ..fffffffffffffffffff.
    ..ffffffffffffffff11f.
    .fff111fffffffffff11f.
    .fff111ffffffffffffff.
    .fff111ffffffffffffff.
    .ffffffffffffffffffff.
    .ffffffffffffffffffff.
    ..fffffffffffffffffff.
    ..fffffffffffffffffff.
    ...ffffffffffffffffff.
    ....fffffffffffffffff.
    .....ffffffffffffffff.
    .......ffffffffffffff.
    ...............ffffff.
    ...................ff.
    `,
img`
    ......................
    ......................
    ......................
    ......................
    ......................
    ..cc...............c..
    ...cc..............c..
    ....cc............cc..
    ......c...........f1..
    ....ff1...........ff..
    ....fff...............
    ....fff...............
    ......................
    ................3333..
    .................33...
    .................fff.f
    .............f..ffffff
    .............ffffffff.
    ..............ffff....
    ......................
    ......................
    ......................
    `,
img`
    ......................
    ......................
    ......................
    ......................
    ......................
    ......................
    ......................
    ......................
    ..................f1..
    ....ff1...........ff..
    ....fff...............
    ....fff...............
    ......................
    .................3333.
    ..................33..
    ......................
    ......................
    ......................
    ..................f...
    .................fff..
    ......................
    ......................
    `,
img`
    ......................
    ......................
    ......................
    ......................
    ......................
    ......................
    ......................
    ......................
    ..................f1..
    ....ff1...........ff..
    ....fff...............
    ....fff...............
    ......................
    .................3333.
    ..................33..
    ......................
    ......................
    ......................
    ..................f...
    .................fff..
    ......................
    ......................
    `,
img`
    ......................
    ......................
    ......................
    ......................
    ......................
    ......................
    ......................
    ......................
    ..................f1..
    ....ff1...........ff..
    ....fff...............
    ....fff...............
    ......................
    .................3333.
    ..................33..
    ......................
    ......................
    ......................
    ..................f...
    .................fff..
    ......................
    ......................
    `,
img`
    ......................
    ......................
    ......................
    ......................
    ......................
    ......................
    ......................
    ......................
    ..................f1..
    ....ff1...........ff..
    ....fff...............
    ....fff...............
    ......................
    .................3333.
    ..................33..
    ......................
    ......................
    ......................
    ..................f...
    .................fff..
    ......................
    ......................
    `
]
costume = [img`
    ...............222..............
    ..............22222.............
    .............2222222............
    ............22222222222.........
    ...........222222222222222222222
    ...........222222222222222222552
    ..........4422222222222222222552
    ........444422222222222222222224
    .......4444442222222222222222224
    ......44444444222222222222222224
    ....4444444444422222222222225544
    ...4444444444444222222222222554.
    ..44444444444444222222222222224.
    .444444444444444422222222222244.
    444444444444444444222222222224..
    444444444444444444222222222224..
    .44444444444444444422222225544..
    ..444444444444444442222222554...
    ...44444444444444444222222224...
    ....4444444444444444222222224...
    .....444444444444444422222224...
    ......44444444444444422225524...
    .......4444444444444442225524...
    .........44444444444444222224...
    .........44444444444444222224...
    ..........444444444444442222....
    ..........444444444444442222....
    ..........44444444444444222.....
    ...........4444444444444422.....
    ............44444444444442......
    ............44444444444444......
    ............4444444444444.......
    ............4444444444444.......
    ............444444444444........
    ............44444444444.........
    ...............44444............
    `, img`
    ...............cccccc...........
    ..............cccccccccc........
    .............ccccccccccc........
    ............cccccc88888ccccccccc
    ...........ccc8888888888cccccccc
    ...........c8888888888888ccccccc
    ..........c88888888888888acccccc
    ........cccc888888888888aaaccccc
    .......cccccc88888888888aacccccc
    ......cccccccc888888888aaacccccc
    ....ccccccccccc8888888aaaacccccc
    ...ccccccccccccc888888aaaaccccc.
    ..cccccccccccccc88888aaaaaccccc.
    .cccccccccccccccc888aaaaacccccc.
    cccccccccccccccccc8aaaaacccccc..
    ccccccccccccccccccaaaaaacccccc..
    .ccccccccccccccccccaaaaccccccc..
    ..cccccccccccccccccaaaacccccc...
    ...ccccccccccccccccaaaccccccc...
    ....ccccccccccccccccaaccccccc...
    .....cccccccccccccccaaccccccc...
    ......ccccccccccccccccccccccc...
    .......cccccccccccccccccccccc...
    .........cccccccccccccccccccc...
    .........cccccccccccccccccccc...
    ..........cccccccccccccccccc....
    ..........cccccccccccccccccc....
    ..........cccccccccccccccccc....
    ...........ccccccccccccccccc....
    ............cccccccccccccc......
    ............cccccccccccccc......
    ............ccccccccccccc.......
    ............ccccccccccccc.......
    ............cccccccccccc........
    ............ccccccccccc.........
    ...............ccccc............
    `]
arms = [img`
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ddddd...................................
    ddddd...................................
    dddddd..................................
    ddddddd.................................
    .ddddddd................................
    ..ddddddd...............................
    ...dddddddd.............................
    ...dddddddddd...........................
    ....dddddddddddd........................
    .....ddddddddddddd......................
    ......ddddddddddddd.....................
    ..........ddddddddd.....................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    `, img`
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ddddd............................999....
    ddddd.........................999998....
    dddddd.......................9999889....
    ddddddd....................99998899.....
    .ddddddd.................999988999......
    ..ddddddd..............9999989999.......
    ...dddddddd......bb..999998899..........
    ...dddddddddd....bb999998899............
    ....dddddddddddd..bb998899..............
    .....dddddddddddddbbb8999...............
    ......dddddddddddddbb9..................
    ..........dddddddddbb...................
    ...............bbb.bbb..................
    ..............bbb...bb..................
    ..............bb........................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    `, img`
    ........................................
    ........................................
    ...............................2222.....
    ..............................222222....
    ............................22222222....
    .........................22222222222....
    ........................222222222222....
    .......................1111122222222....
    ......................1111111122222.....
    ddddd............222211111111112222.....
    ddddd.........222222111111111111122.....
    dddddd.....22222222111111ff1111112......
    ddddddd....2222222211111f99f111111......
    .ddddddd...2222222111111f99f11111.......
    ..ddddddd.......221111111ff111111.......
    ...dddddddd.....1111111111111111........
    ...dddddddddd..11111111111111122........
    ....dddddddddddd1111111111111122........
    .....ddddddddddddd11111111111222........
    ......ddddddddddddd1111111112222........
    ..........ddddddddd1111111122222........
    .............2111111111111122222........
    ...........222211111111111..222.........
    ..........2222.1111111111...222.........
    ...........222...1111111.....22.........
    ............2...2211111......2..........
    ...............222.11...................
    ...............222......................
    ................2.......................
    ........................................
    `, img`
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ddddd...................................
    ddddd...................................
    dddddd..................................
    ddddddd.................................
    .ddddddd................................
    ..ddddddd...............................
    ...dddddddd.............................
    ...dddddddddd...........................
    ....dddddddddddd........................
    .....ddddddddddddd......................
    ......ddddddddddddd.....................
    ..........ddddddddd.....................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    `, img`
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ddddd...................................
    ddddd...................................
    dddddd..................................
    ddddddd.................................
    .ddddddd................................
    ..ddddddd...............................
    ...dddddddd.............................
    ...dddddddddd...........................
    ....dddddddddddd........................
    .....ddddddddddddd......................
    ......ddddddddddddd.....................
    ..........ddddddddd.....................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    ........................................
    `]
setup()
game.onUpdateInterval(2000, function () {
    if (gameStarted) {
        projectile = sprites.createProjectileFromSide(img`
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ....6666666.....
            ...6666666666...
            ..667777777766..
            .66777777777766.
            6777777777777766
            771f1777771f1776
            7711177777111777
            7777777777777777
            7777777777777777
            `, -50, 0)
        animation.runImageAnimation(
        projectile,
        [img`
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ...6666666666...
            ..667777777766..
            .66777777777766.
            6777777777777766
            771f1777771f1776
            7711177777111777
            7777777777777777
            7777777777777777
            `,img`
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ....66666666....
            ...6666666666...
            ..66ffffffff66..
            ..6f66666666f66.
            .6f6777777776f6.
            .667777777777666
            6777777777777766
            771f1777771f1776
            7711177777111777
            7777777777777777
            7777777777777777
            `,img`
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ....6666666.....
            ...6f1f1f1f66...
            ..66fffffffff6..
            .6ff1f1f1f1fff6.
            .6ff666666661f6.
            6f16777777776f66
            6667777777777666
            6777777777777766
            771f1777771f1776
            7711177777111777
            7777777777777777
            7777777777777777
            `,img`
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ....66666666....
            ...6666666666...
            ..66ffffffff66..
            ..6f66666666f66.
            .6f6777777776f6.
            .667777777777666
            6777777777777766
            771f1777771f1776
            7711177777111777
            7777777777777777
            7777777777777777
            `],
        100,
        true
        )
        projectile.bottom = 120
    }
})
game.onUpdateInterval(200, function () {
    if (gameStarted) {
        for (let value of sprites.allOfKind(SpriteKind.Projectile)) {
            if (Math.percentChance(10)) {
                animation.runImageAnimation(
                value,
                [img`
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ...6666666666...
                    ..667777777766..
                    .66777777777766.
                    6777777777777766
                    771f1777771f1776
                    7711177777111777
                    7777777777777777
                    7777777777777777
                    `,img`
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ....6666666.....
                    ...6f1f1f1f66...
                    ..66fffffffff6..
                    .6ff1f1f1f1fff6.
                    .6ff666666661f6.
                    6f16777777776f66
                    6667777777777666
                    6777777777777766
                    771f1777771f1776
                    7711177777111777
                    7777777777777777
                    7777777777777777
                    `,img`
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ........2.2.....
                    .........2......
                    .........2......
                    ........22......
                    ........22......
                    ........22......
                    ........2.......
                    ........2.......
                    ....6662266.....
                    ...6f1f221f66...
                    ..66fff22ffff6..
                    .6ff1f1f1f1fff6.
                    .6ff666666661f6.
                    6f16777777776f66
                    6667777777777666
                    6777777777777766
                    771f1777771f1776
                    7711177777111777
                    7777777777777777
                    7777777777777777
                    `,img`
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ......2.2.......
                    .......2........
                    .......2........
                    ......22........
                    ......22........
                    ......22........
                    .......22.......
                    .......22.......
                    .......22.......
                    .......22.......
                    ....6662266.....
                    ...6f1f221f66...
                    ..66fff22ffff6..
                    .6ff1f1f1f1fff6.
                    .6ff666666661f6.
                    6f16777777776f66
                    6667777777777666
                    6777777777777766
                    771f1777771f1776
                    7711177777111777
                    7777777777777777
                    7777777777777777
                    `,img`
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ........2.2.....
                    .........2......
                    .........2......
                    ........22......
                    ........22......
                    ........22......
                    .......22.......
                    .......22.......
                    .......22.......
                    .......22.......
                    ......222.......
                    ......2.........
                    ......222.......
                    .......22.......
                    .......22.......
                    .......22.......
                    .......22.......
                    ....6662266.....
                    ...6f1f221f66...
                    ..66fff22ffff6..
                    .6ff1f1f1f1fff6.
                    .6ff666666661f6.
                    6f16777777776f66
                    6667777777777666
                    6777777777777766
                    771f1777771f1776
                    7711177777111777
                    7777777777777777
                    7777777777777777
                    `,img`
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    .....2.2........
                    ......2.........
                    ......2.........
                    ......22........
                    ......22........
                    ......22........
                    .......22.......
                    .......22.......
                    .......22.......
                    .......22.......
                    .......22.......
                    ......22........
                    ......22........
                    ......22........
                    .......22.......
                    .......22.......
                    .......22.......
                    .......22.......
                    .......22.......
                    .......22.......
                    ....6662266.....
                    ...6f1f221f66...
                    ..66fff22ffff6..
                    .6ff1f1f1f1fff6.
                    .6ff666666661f6.
                    6f16777777776f66
                    6667777777777666
                    6777777777777766
                    771f1777771f1776
                    7711177777111777
                    7777777777777777
                    7777777777777777
                    `,img`
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ......2.2.......
                    .......2........
                    .......2........
                    ......22........
                    ......22........
                    ......22........
                    .......22.......
                    .......22.......
                    .......22.......
                    .......22.......
                    ....6662266.....
                    ...6f1f221f66...
                    ..66fff22ffff6..
                    .6ff1f1f1f1fff6.
                    .6ff666666661f6.
                    6f16777777776f66
                    6667777777777666
                    6777777777777766
                    771f1777771f1776
                    7711177777111777
                    7777777777777777
                    7777777777777777
                    `,img`
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ....6626266.....
                    ...6f1f221f66...
                    ..66fff2fffff6..
                    .6ff1f1f1f1fff6.
                    .6ff666666661f6.
                    6f16777777776f66
                    6667777777777666
                    6777777777777766
                    771f1777771f1776
                    7711177777111777
                    7777777777777777
                    7777777777777777
                    `,img`
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ................
                    ....66666666....
                    ...6666666666...
                    ..66ffffffff66..
                    ..6f66666666f66.
                    .6f6777777776f6.
                    .667777777777666
                    6777777777777766
                    771f1777771f1776
                    7711177777111777
                    7777777777777777
                    7777777777777777
                    `],
                75,
                true
                )
                value.bottom = 120
                value.setKind(SpriteKind.longSnake)
                value.lifespan = 75 * 9
            }
        }
    }
})
